# RSUD20K: original road scenes for Stage-1 object detection.
path: C:/Users/faalv/Desktop/University stuff/10th sem/CVPR/Project1/Datasets/rsud20k
train: images/train
val: images/val
test: images/test

names:
  0: person
  1: rickshaw
  2: rickshaw_van
  3: auto_rickshaw
  4: truck
  5: pickup_truck
  6: private_car
  7: motorcycle
  8: bicycle
  9: bus
  10: micro_bus
  11: covered_van
  12: human_hauler
