"""Shared manifest writer for the figure-building scripts.

Scripts 11 and 12 both produce figures and both need to describe them in
figures/FIGURES.txt. Writing that file directly from either script means
re-running one on its own silently drops the other's entries, which is exactly
what happened once during development. Routing both through an accumulating
JSON store fixes that: FIGURES.txt is always rendered from the union.
"""

from __future__ import annotations

import json
from pathlib import Path

HEADER = (
    "FIGURE MANIFEST\n"
    "Two-Stage Bangladesh Vehicle Recognition (RSUD20K)\n"
    "Generated by scripts/11_build_figures.py and scripts/12_build_inference_figures.py\n"
    "Every figure is saved as both .png (300 dpi) and .pdf (vector, for LaTeX).\n"
)


def wrap(text: str, width: int = 76) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        if len(current) + len(word) + 1 > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines


def write_manifest(fig_dir: Path, entries) -> int:
    """Merge `entries` into the store, re-render FIGURES.txt, return the total."""
    store = fig_dir / "_manifest.json"
    catalogue: dict[str, str] = {}
    if store.exists():
        catalogue = json.loads(store.read_text(encoding="utf-8"))

    catalogue.update(dict(entries))
    store.write_text(json.dumps(catalogue, indent=4), encoding="utf-8")

    out = [HEADER, "=" * 78, "", ""]
    for name in sorted(catalogue):
        out.append(name)
        out.append("-" * len(name))
        out.extend(wrap(catalogue[name]))
        out.append("")

    (fig_dir / "FIGURES.txt").write_text("\n".join(out), encoding="utf-8")
    return len(catalogue)
